# fly.toml app configuration file generated for tabletoptally on 2023-10-10T15:51:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tabletoptally"
primary_region = "sea"
console_command = "/rails/bin/rails console"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
